<a href="https://colab.research.google.com/github/paulaprado1904/DataScience/blob/main/Data_Science_AdaCoders2024Santander.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

1. Tipo de Dado:

**Listas:** podem armazenar elementos de diferentes tipos de dados, como números, strings, booleanos e até mesmo outras listas. Isso as torna versáteis para tarefas gerais.

**Arrays NumPy:** são homogêneos, ou seja, todos os elementos devem ser do mesmo tipo de dado, como int, float ou bool. Isso os torna mais eficientes para cálculos matemáticos.


2. Funcionalidade:

**Listas:** oferecem funções integradas para tarefas como inserção, remoção, ordenação e fatiamento. Elas são flexíveis e fáceis de usar para manipulação geral de dados.

**Arrays NumPy:** fornecem funções avançadas para operações matemáticas, como álgebra linear, estatística e processamento de sinal. Elas são mais adequadas para análise e processamento de dados numéricos.

#Principais Funções Usadas no NumPy:

O NumPy oferece uma vasta gama de funções para diversos propósitos, desde a criação e manipulação de arrays até cálculos matemáticos complexos. Abaixo, listo algumas das funções mais utilizadas:

1. Criação de Arrays:

`np.array():` Cria um array a partir de um objeto Python iterável.

`np.zeros():` Cria um array preenchido com zeros.

`np.ones():` Cria um array preenchido com uns.

`np.empty():` Cria um array vazio (sem valores inicializados).

`np.arange():` Cria um array com valores sequenciais.

`np.linspace():` Cria um array com valores espaçados linearmente.

2. Manipulação de Arrays:

`np.shape():` Retorna a forma (dimensões) de um array.

`np.dtype():` Retorna o tipo de dados de um array.

`np.size(): `Retorna o número total de elementos em um array.

`np.reshape():` Rearranja os elementos de um array em uma nova forma.

`np.ravel():` Converte um array multidimensional em um array unidimensional.

`np.stack():` Combina arrays ao longo de um novo eixo.

`np.hstack():` Combina arrays horizontalmente (concatena colunas).

`np.vstack(): `Combina arrays verticalmente (concatena linhas).

3. Seleção de Elementos:

[]: Indexação de elementos por posição ou intervalo.
:: Fatiamento para selecionar subconjuntos de um array.

`np.where():` Seleciona elementos com base em uma condição.

`np.isin():` Verifica se elementos específicos estão presentes em um array.

4. Operações Matemáticas:

(+ - * / // ** %): Operadores aritméticos básicos.

`np.power():` Potenciação.

`np.log():` Logaritmo.

`np.exp():` Exponenciação.

`np.abs():` Valor absoluto.

`np.sqrt():` Raiz quadrada.

`np.round():` Arredondamento.

`np.floor():` Arredondamento para baixo.

`np.ceil():` Arredondamento para cima.

5. Funções Estatísticas:

`np.mean():` Média aritmética.

`np.median():` Mediana.

`np.std():` Desvio padrão.

`np.var():` Variância.

`np.sum():` Soma dos elementos.

`np.min():` Mínimo.

`np.max():` Máximo.

`np.cumsum():` Soma acumulada.

`np.diff():` Diferença entre elementos adjacentes.

6. Álgebra Linear:

`np.dot(): `Produto escalar e produto matricial.

`np.linalg.inv():` Inversa de uma matriz.

`np.linalg.det():` Determinante de uma matriz.

`np.linalg.eig():` Autovalores e autovetores de uma matriz.

`np.linalg.solve():` Solução de sistemas lineares.

7. Geração de Números Aleatórios:

`np.random.rand():` Números aleatórios uniformes entre 0 e 1.

`np.random.randn():` Números aleatórios com distribuição normal.

`np.random.randint():` Números aleatórios inteiros dentro de um intervalo especificado.

`np.random.choice():` Amostragem aleatória de um array.

`np.random.shuffle():` Embaralha os elementos de um array aleatoriamente.

8. Funções Adicionais:

`np.savetxt():` Salva um array em um arquivo de texto.

`np.loadtxt():` Carrega um array de um arquivo de texto.

`np.polyfit():` Regressão polinomial.

`np.fft.fft()` e `np.fft.ifft():` Transformada rápida de Fourier (FFT) e inversa.

#Principais Funções Usadas no Pandas:
O Pandas oferece uma vasta gama de funções para manipulação e análise de dados em tabelas (DataFrames). Abaixo, listo algumas das funções mais utilizadas, organizadas por categorias:

1. Leitura e Gravação de Dados:

- `pd.read_csv()`: Lê um arquivo CSV e o retorna como um DataFrame.
- `pd.read_excel()`: Lê um arquivo Excel e o retorna como um DataFrame.
- `pd.read_json()`: Lê um arquivo JSON e o retorna como um DataFrame.
- `pd.to_csv()`: Salva um DataFrame em um arquivo CSV.
- `pd.to_excel()`: Salva um DataFrame em um arquivo Excel.
- `pd.to_json()`: Salva um DataFrame em um arquivo JSON.

2. Seleção e Filtragem de Dados:

- `[]`: Seleciona colunas ou linhas por índice ou nome.
- `.loc()`: Seleciona elementos por rótulo de índice e/ou colunas.
- `.iloc()`: Seleciona elementos por posição de índice e/ou colunas.
- `.query()`: Seleciona elementos com base em uma expressão booleana.
- `.isin()`: Seleciona elementos que pertencem a um conjunto específico.

3. Manipulação de Dados:

- `.dropna()`: Remove linhas com valores ausentes (NaN).
- `.fillna()`: Preenche valores ausentes (NaN) com um valor específico.
- `.replace()`: Substitui valores em um DataFrame por outros valores.
- `.astype()`: Converte o tipo de dados de uma coluna.
- `.nunique()`: Retorna o número de valores únicos em uma coluna.
- `.apply()`: Aplica uma função a cada elemento de uma coluna ou DataFrame.

4. Agregação e Estatística Descritiva:

- `.groupby()`: Agrupa o DataFrame por uma ou mais colunas.
- `.agg()`: Aplica funções de agregação (soma, média, etc.) aos grupos.
- `.describe()`: Retorna estatísticas descritivas do DataFrame.
- `.head()`: Mostra as primeiras linhas do DataFrame.
- `.tail()`: Mostra as últimas linhas do DataFrame.

5. Junção e Combinação de Dados:

- `.merge()`: Combina dois DataFrames com base em uma coluna comum.
- `.concat()`: Concatena dois DataFrames verticalmente ou horizontalmente.
- `.append()`: Adiciona linhas de um DataFrame a outro.

6. Criação de Novas Colunas:

- `[]` com atribuição: Cria uma nova coluna com base em outra coluna ou expressão.
- `.assign()`: Cria uma ou mais novas colunas com base em funções ou valores.

In [8]:
import pandas as pd

In [9]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
import pandas as pd

taxis = pd.read_csv('taxis.csv')
taxis.head()    # mostra as 5 primeiras linhas da tabela

taxis['dropoff_borough'].value_counts()     #conta a quantidade de vez que cada valor de 'dropoff_borough' aparece dentro da tabela taxis


#Validando uma hipótese:

# Vizinhança em que as casas constumam ser mais caras oferecem melhores gorjetas?

taxis.groupby(['dropoff_borough'])['tip'].agg(['mean','median'])     # agrupa 'tip' (campo/valor que quero saber) por 'dropoff_borough' - lugar de destino - e as agregações que quero que faça: 'mean', 'median'

#Passo a Passo

#taxis.groupby(['dropoff_borough']):
#A função groupby do Pandas agrupa os dados no DataFrame taxis com base nos valores únicos na coluna dropoff_borough.
#O resultado é um objeto GroupBy, que contém informações sobre como os dados são divididos em grupos.

#['tip']:
#Após agrupar os dados, selecionamos a coluna tip, que contém os valores das gorjetas.
#Isto indica que as operações subsequentes serão aplicadas apenas a esta coluna.

#.agg(['mean', 'median']):
#A função agg é usada para aplicar múltiplas funções de agregação a uma ou mais colunas.
#Passando uma lista de funções ['mean', 'median'], estamos pedindo para calcular a média (mean) e a mediana (median) das gorjetas para cada grupo de dropoff_borough.

In [87]:
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Sao paulo.xlsx') # Lê um arquivo Excel chamado 'Sao_paulo.xlsx' e o retorna como um DataFrame.

#df: É a variável que irá armazenar os dados lidos do arquivo Excel. Após a execução dessa linha, df se torna um DataFrame, que é uma estrutura de dados bidimensional (semelhante a uma tabela) usada para armazenar e manipular dados em Python com a biblioteca Pandas.

#pd: É a convenção comum usada para importar a biblioteca Pandas. Ao importar Pandas usando import pandas as pd, estamos criando um alias (pd) para facilitar o uso das funções da biblioteca.

#read_excel: É uma função da biblioteca Pandas (pd) que lê o conteúdo de um arquivo Excel (.xlsx) e o converte em um DataFrame.

df          # retorna o conteúdo do dataframe

,Street,City,propertycard__detailvalue,quartos,banheiros,vagas,price
0,"Avenida Itacira, 255","Planalto Paulista, São Paulo",1000,4,8,6,R$ 7.000.000
1,"Rua Aurelia Perez Alvarez, 42","Jardim dos Estados, São Paulo",469-524,3-6,3-6,4,R$ 3.700.000
2,Rua Alba Valdez,"Jardim Reimberg, São Paulo",125,4,3,2,R$ 380.000
3,"Jardim Morumbi, São Paulo",SP,310,3,2,4,R$ 685.000
4,"Rua Tobias Barreto, 195","Mooca, São Paulo",100,3,2,2,R$ 540.000
...,...,...,...,...,...,...,...
10028,Rua Tapuçu,"Vila Sofia, São Paulo",90,2,2,2,R$ 665.000
10029,Rua Guararema,"Bosque da Saúde, São Paulo",600,8,7,5,R$ 2.300.000
10030,Rua Estero Belaco,"Vila da Saúde, São Paulo",200,3,3,6,R$ 1.050.000
10031,"Rua Manuel Onha, , 514","Vila Oratório, São Paulo",180,3,2,2,R$ 2.200\n /Mês
10032,"Rua Barão de Tramandaí, 0","Vila Alpina, São Paulo",117,3,2,2,R$ 270.000

# O que é e como é um DataFrame?

Um DataFrame é uma estrutura de dados bidimensional do Pandas, que se assemelha a uma tabela em uma base de dados ou a uma planilha do Excel. Ele possui colunas e linhas rotuladas, onde cada coluna pode conter um tipo de dado diferente (números, strings, datas, etc.).

###Características do DataFrame:
**Etiquetas (Rótulos):** Tanto as linhas quanto as colunas possuem rótulos. As colunas são acessadas através de seus nomes e as linhas geralmente são acessadas por índices numéricos.

**Heterogeneidade:** Diferentes colunas podem conter diferentes tipos de dados (inteiros, floats, strings, etc.).

**Alinhamento Automático:**  Operações entre DataFrames automaticamente alinham os dados baseados nos rótulos das linhas e colunas.

*Exemplo de Criação de um DataFrame:*
Aqui está um exemplo de como criar um DataFrame a partir de um dicionário:
```
import pandas as pd

# Dados para o DataFrame
data = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [28, 34, 29],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

# Criação do DataFrame
df = pd.DataFrame(data)

# Exibição do DataFrame
print(df)
```

![Captura de tela 2024-06-13 092022.png]()

#Operações Comuns com DataFrames:
Seleção de Colunas: df['Nome'] retorna a coluna 'Nome'.

Seleção de Linhas: df.loc[0] retorna a primeira linha.

Filtragem: df[df['Idade'] > 30] retorna um DataFrame com linhas onde a idade é maior que 30.

Resumo Estatístico: df.describe() retorna estatísticas descritivas do DataFrame.

Adicionar Colunas: df['Salário'] = [50000, 60000, 55000] adiciona uma nova coluna chamada 'Salário'.

O DataFrame é uma ferramenta poderosa e flexível para manipulação e análise de dados em Python, muito utilizada em ciência de dados, análise financeira, processamento de dados, e muitas outras áreas.

In [89]:
# Percebe-se que há dados como preço por mês, saindo do padrão, devemos corrigir

df.loc[10031]       # acessa a linha 10031
auxiliar = df.loc[10031]
#df: This is your Pandas DataFrame that holds your tabular data.
# .loc: This is an attribute of the DataFrame that allows you to access rows and columns by their labels (index labels for rows and column names for columns).
# [10031]: This is the index label of the row you want to retrieve.

In [90]:
# definindo uma função para 'limpar' dados

def limpa_preco(linha):
  linha['price'] = linha ['price'].replace('R$', '')
  linha['price'] = linha['price'].replace('\n', '')
  linha['price'] = linha['price'].replace('/Mês', '')
  linha['price'] = linha['price'].replace('/Ano', '')
  linha['price'] = linha['price'].replace('/Dia', '')
  linha['price'] = linha['price'].replace('                     ', '')
  linha['price'] = linha['price'].replace(' ', '')
  return linha

In [91]:
limpa_preco(auxiliar)
#auxiliar

Street                          Rua Manuel Onha, , 514
City                          Vila Oratório, São Paulo
propertycard__detailvalue                           180
quartos                                               3
banheiros                                             2
vagas                                                 2
price                                             2.200
Name: 10031, dtype: object

In [92]:
df.apply(lambda x: limpa_preco(x), axis=1)

,Street,City,propertycard__detailvalue,quartos,banheiros,vagas,price
0,"Avenida Itacira, 255","Planalto Paulista, São Paulo",1000,4,8,6,7.000.000
1,"Rua Aurelia Perez Alvarez, 42","Jardim dos Estados, São Paulo",469-524,3-6,3-6,4,3.700.000
2,Rua Alba Valdez,"Jardim Reimberg, São Paulo",125,4,3,2,380.000
3,"Jardim Morumbi, São Paulo",SP,310,3,2,4,685.000
4,"Rua Tobias Barreto, 195","Mooca, São Paulo",100,3,2,2,540.000
...,...,...,...,...,...,...,...
10028,Rua Tapuçu,"Vila Sofia, São Paulo",90,2,2,2,665.000
10029,Rua Guararema,"Bosque da Saúde, São Paulo",600,8,7,5,2.300.000
10030,Rua Estero Belaco,"Vila da Saúde, São Paulo",200,3,3,6,1.050.000
10031,"Rua Manuel Onha, , 514","Vila Oratório, São Paulo",180,3,2,2,2.200
10032,"Rua Barão de Tramandaí, 0","Vila Alpina, São Paulo",117,3,2,2,270.000

In [97]:
def ajusta_alugueis(linha):
  linha['price'] = str(linha['price']).replace('.', '')
  preco = int(linha['price'])
  if(preco < 10000):
    preco = preco * 200
  linha['price'] = preco
  return linha

In [95]:
ajusta_alugueis(auxiliar)

Street                          Rua Manuel Onha, , 514
City                          Vila Oratório, São Paulo
propertycard__detailvalue                           180
quartos                                               3
banheiros                                             2
vagas                                                 2
price                                            440000
Name: 10031, dtype: object

In [98]:
df.apply(lambda x: ajusta_alugueis(x), axis=1)

,Street,City,propertycard__detailvalue,quartos,banheiros,vagas,price
0,"Avenida Itacira, 255","Planalto Paulista, São Paulo",1000,4,8,6,7000000
1,"Rua Aurelia Perez Alvarez, 42","Jardim dos Estados, São Paulo",469-524,3-6,3-6,4,3700000
2,Rua Alba Valdez,"Jardim Reimberg, São Paulo",125,4,3,2,380000
3,"Jardim Morumbi, São Paulo",SP,310,3,2,4,685000
4,"Rua Tobias Barreto, 195","Mooca, São Paulo",100,3,2,2,540000
...,...,...,...,...,...,...,...
10028,Rua Tapuçu,"Vila Sofia, São Paulo",90,2,2,2,665000
10029,Rua Guararema,"Bosque da Saúde, São Paulo",600,8,7,5,2300000
10030,Rua Estero Belaco,"Vila da Saúde, São Paulo",200,3,3,6,1050000
10031,"Rua Manuel Onha, , 514","Vila Oratório, São Paulo",180,3,2,2,440000
10032,"Rua Barão de Tramandaí, 0","Vila Alpina, São Paulo",117,3,2,2,270000

In [99]:
df

,Street,City,propertycard__detailvalue,quartos,banheiros,vagas,price
0,"Avenida Itacira, 255","Planalto Paulista, São Paulo",1000,4,8,6,7000000
1,"Rua Aurelia Perez Alvarez, 42","Jardim dos Estados, São Paulo",469-524,3-6,3-6,4,3700000
2,Rua Alba Valdez,"Jardim Reimberg, São Paulo",125,4,3,2,380000
3,"Jardim Morumbi, São Paulo",SP,310,3,2,4,685000
4,"Rua Tobias Barreto, 195","Mooca, São Paulo",100,3,2,2,540000
...,...,...,...,...,...,...,...
10028,Rua Tapuçu,"Vila Sofia, São Paulo",90,2,2,2,665000
10029,Rua Guararema,"Bosque da Saúde, São Paulo",600,8,7,5,2300000
10030,Rua Estero Belaco,"Vila da Saúde, São Paulo",200,3,3,6,1050000
10031,"Rua Manuel Onha, , 514","Vila Oratório, São Paulo",180,3,2,2,440000
10032,"Rua Barão de Tramandaí, 0","Vila Alpina, São Paulo",117,3,2,2,270000

In [108]:
df['price']

0        7000000
1        3700000
2         380000
3         685000
4         540000
          ...
10028     665000
10029    2300000
10030    1050000
10031     440000
10032     270000
Name: price, Length: 10033, dtype: object

#**Criando Gráficos**